### ISSUE TITLE
Few things for convenience

### ISSUE THREAD

**Issue by Fletscherrrr** [kkrruumm/void-install-script#1]
Hey, I really like your script :>

There are a few more things that 'could' be covered by it tho:
Choice for gaming - specifically steam, lutris + dependencies and wine generally though its understandable if you wouldnt want to include it
Choice for vm out of box(virt-manager for example)

**Comment by kkrruumm** [comment]
I could see adding some "post-install modules" options to deploy more specific configs for things like virt-manager and maybe some other things, Steam/Lutris might be a little bit too specific for this installer but I'm not *completely* against it.

 Maybe an option to enable multilib and non-free repositories and an "extra packages" section to go with it so you can enter the packages you'd like to install that aren't included as an option in the installer?

This also brings the question of "should this be a TUI instead?" to better organize these options if we're adding a bunch more instead of adding more prompts.

It may be time to transition this into a Dialog type installer.

**Comment by kkrruumm** [comment]
@Fletscherrrr The modules system I mentioned has been added, I decided not to include a module for steam/lutris/wine, though I did include one to configure libvirt and qemu, though lacking virt-manager as some people may choose to use another GUI for this.

Closing this issue with this comment, do let me know if there's anything else.
